# Maple Mover - Streamlit Configuration
# Production-ready Streamlit settings

[server]
# Server configuration
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = true
enableXsrfProtection = false

# File watching
fileWatcherType = "poll"
runOnSave = true

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Maple Mover theme
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[client]
# Client-side settings
showErrorDetails = true
toolbarMode = "minimal"

[runner]
# Runner configuration
magicEnabled = true